name: ci

on:
  push:
  pull_request:

env:
  NODE_VERSION: 22.x


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run check
        run: pnpm typecheck
      - name: Run lint
        run: pnpm lint
